const initState = {
  events: {
    month: {
    //   november: [
    //     {
    //       id: 5,
    //       date: '27th',
    //       day: 'Friday',
    //       month: 'November',
    //       start: '2pm',
    //       end: '4pm',
    //       title: '"Mitch Lies"  - Guitar, Vocals',
    //     },
    //     {
    //       id: 6,
    //       date: '9th',
    //       day: 'Saturday',
    //       month: 'November',
    //       start: '6pm',
    //       end: '9pm',
    //       title: '"Midnight Pass" - Jazz',
    //     },
    //     {
    //       id: 7,
    //       date: '10th',
    //       day: 'Sunday',
    //       month: 'November',
    //       start: '2pm',
    //       end: '4pm',
    //       title: '"Sig Paulson" - Solo Guitar & Vocals',
    //     },
    //     {
    //       id: 8,
    //       date: '15th',
    //       day: 'Friday',
    //       month: 'November',
    //       start: '6pm',
    //       end: '9pm',
    //       title: '"Ted Vaughn" - Blues Band',
    //     },
    //     {
    //       id: 9,
    //       date: '16th',
    //       day: 'Saturday',
    //       month: 'November',
    //       start: '6pm',
    //       end: '9pm',
    //       title: '"Orvil Ivie & Smiley Mike Duo" - Smooth Jazz',
    //     },
    //     {
    //       id: 10,
    //       date: '17th',
    //       day: 'Sunday',
    //       month: 'November',
    //       start: '2pm',
    //       end: '4pm',
    //       title: '"Orvil Ivie" - Solo Guitar & Vocals',
    //     },
    //     {
    //       id: 11,
    //       date: '22nd',
    //       day: 'Friday',
    //       month: 'November',
    //       start: '6pm',
    //       end: '9pm',
    //       title: '"Leanne McClellan Band"  - Classic R&R',
    //     },
    //     {
    //       id: 12,
    //       date: '23rd',
    //       day: 'Saturday',
    //       month: 'November',
    //       start: '6pm',
    //       end: '9pm',
    //       title: '"Orvil Ivei/Mike Renwick Duo" - Smooth Jazz, Santana',
    //     },
    //     {
    //       id: 13,
    //       date: '24th',
    //       day: 'Sunday',
    //       month: 'November',
    //       start: '2pm',
    //       end: '4pm',
    //     title: '"Mitch Lies" - Solo Guitar, Vocals',
    //     },
    //     {
    //       id: 14,
    //       date: '30th',
    //       day: 'Saturday',
    //       month: 'November',
    //       start: '6pm',
    //       end: '9pm',
    //       title: '"Dead Band" - Grateful Dead',
    //     },
    //   ],
      december: [
        {
          id: 15,
          date: '1st',
          day: 'Sunday',
          month: 'December',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie" - Solo Guitar & Vocals',
        },
        {
          id: 16,
          date: '6th',
          day: 'Friday',
          month: 'December',
          start: '6pm',
          end: '9pm',
          title: '"Joanne Broh Blues Band" - Blues',
        },
        {
          id: 17,
          date: '7th',
          day: 'Saturday',
          month: 'December',
          start: '6pm',
          end: '9pm',
          title: '"Gil Reynolds Band" - Redgate Wine Club Christmas Party Wine Pickup',
        },
        {
          id: 18,
          date: '8th',
          day: 'Sunday',
          month: 'December',
          start: '1pm',
          end: '4pm',
          title: 'Wine Club Pick Up Party',
        },
        {
          id: 19,
          date: '8th',
          day: 'Sunday',
          month: 'December',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie" - Solo Guitar & Vocals',
        },
        {
          id: 20,
          date: '13th',
          day: 'Friday',
          month: 'December',
          start: '6pm',
          end: '9pm',
          title: '"Midnight Pass"  - Steve\'s Birthday Party!',
        },
        {
          id: 21,
          date: '14th',
          day: 'Saturday',
          month: 'December',
          start: '6pm',
          end: '9pm',
          title: '"Orvil Ivie Trio" - Smooth Jazz',
        },
        {
          id: 22,
          date: '14th',
          day: 'Saturday',
          month: 'December',
          start: '2pm',
          end: '7pm',
          title: '"Spitit Mountain Annual Holiday Wine & Spirits Fair" - We will be at the 2019 ANNUAL HOLIDAY WINE & SPIRITS FAIR at Spirit Mountain Casino. Public event is from 2 – 7 PM in the Event Center with live entertainment. Admission is free. Vendors will consist of Oregon wineries, distillers, brewers, gourmet food, artist, lifestyle & craft.',
        },
        {
          id: 23,
          date: '15th',
          day: 'Sunday',
          month: 'December',
          start: '2pm',
          end: '4pm',
          title: '"Patrick Anderson"  - Classic R&R',
        },
        {
          id: 24,
          date: '20th',
          day: 'Friday',
          month: 'December',
          start: '6pm',
          end: '9pm',
          title: '"Ted Vaughn" - Blues Band',
        },
        {
          id: 25,
          date: '21st',
          day: 'Saturday',
          month: 'December',
          start: '6pm',
          end: '9pm',
          title: '"Dead Band" - Grateful Dead',
        },
        {
          id: 26,
          date: '22nd',
          day: 'Sunday',
          month: 'December',
          start: '2pm',
          end: '4pm',
          title: '"Mitch Lies" - Solo Guitar, Vocals',
        },
        {
          id: 27,
          date: '28th',
          day: 'Saturday',
          month: 'December',
          start: '2pm',
          end: '4pm',
          title: '"Round House" - Bluegrass',
        },
      ],
      january: [
        {
          id: 1,
          date: '12th',
          day: 'Sunday',
          month: 'January',
          start: '2pm',
          end: '4pm',
          title: '“Ronnie Kay & Uncle Rey ”',
        },
      ],
    },
  },
};

const eventReducer = (state = initState) => {
  return state;
}

export default eventReducer;
