const initState = {
  // TODO: incorporate link to artist site if available
  events: {
    month: {
      june: [
        {
          id: 4,
          date: '12th',
          day: 'Friday',
          month: 'June',
          start: '6pm',
          end: '9pm',
          title: '"Rewind"',
        },
        {
          id: 5,
          date: '13th',
          day: 'Saturday',
          month: 'June',
          start: '6pm',
          end: '9pm',
          title: '"Orvil Ivie / Mike Renwick Duo"',
        },
        {
          id: 11,
          date: '14th',
          day: 'Sunday',
          month: 'June',
          start: '2pm',
          end: '4pm',
          title: '"Mitch Lies"',
        },
        {
          id: 6,
          date: '19th',
          day: 'Friday',
          month: 'June',
          start: '6pm',
          end: '9pm',
          title: '"Ted Vaughn Blues Band"',
        },
        {
          id: 7,
          date: '20th',
          day: 'Saturday',
          month: 'June',
          start: '6pm',
          end: '9pm',
          title: '"Orvil Ivie / Mike Renwick Duo"',
        },
        {
          id: 9,
          date: '26th',
          day: 'Friday',
          month: 'June',
          start: '2pm',
          end: '4pm',
          title: '"Joanne Broh Blues"',
        },
        {
          id: 10,
          date: '27th',
          day: 'Saturday',
          month: 'June',
          start: '6pm',
          end: '9pm',
          title: '"The Dead Band"',
        },
        {
          id: 11,
          date: '28th',
          day: 'Sunday',
          month: 'June',
          start: '2pm',
          end: '4pm',
          title: '"Sig Paulson"',
        },
      ],
      july: [
        {
          id: 1,
          date: '3rd',
          day: 'Friday',
          month: 'July',
          start: '6pm',
          end: '9pm',
          title: '"Ted Vaughn Blues Band"',
        },
        {
          id: 2,
          date: '4th',
          day: 'Saturday',
          month: 'July',
          start: '6pm',
          end: '9pm',
          title: '"Roundhouse"',
        },
        {
          id: 11,
          date: '5th',
          day: 'Sunday',
          month: 'July',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 3,
          date: '11th',
          day: 'Saturday',
          month: 'July',
          start: '2pm',
          end: '4pm',
          title: '"Out of This World Band"',
        },
        {
          id: 4,
          date: '12th',
          day: 'Sunday',
          month: 'July',
          start: '2pm',
          end: '4pm',
          title: '"Mitch Lies"',
        },
        {
          id: 12,
          date: '17th',
          day: 'Friday',
          month: 'July',
          start: '6pm',
          end: '9pm',
          title: '"Long Gone Band"',
        },
        {
          id: 5,
          date: '18th',
          day: 'Saturday',
          month: 'July',
          start: '6pm',
          end: '9pm',
          title: '"Martin Gerschwitz"',
        },
        {
          id: 6,
          date: '19th',
          day: 'Sunday',
          month: 'July',
          start: '1pm',
          end: '4pm',
          title: '"Martin Gerschwitz"',
        },
        {
          id: 7,
          date: '24th',
          day: 'Friday',
          month: 'July',
          start: '2pm',
          end: '4pm',
          title: '"DRTR Blues Band"',
        },
        {
          id: 8,
          date: '25th',
          day: 'Saturday',
          month: 'July',
          start: '2pm',
          end: '4pm',
          title: '"Joanne Broh Band"',
        },
        {
          id: 10,
          date: '31st',
          day: 'Friday',
          month: 'July',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie Trio"',
        },
      ],
      august: [
        {
          id: 1,
          date: '1st',
          day: 'Saturday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"The Dead Band"',
        },
        {
          id: 2,
          date: '7th',
          day: 'Friday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"Out of This World Band"',
        },
        {
          id: 3,
          date: '8th',
          day: 'Saturday',
          month: 'August',
          start: '',
          end: 'Closed to Public',
          title: 'Private Wedding',
          special: 'Closed to Public',
        },
        {
          id: 4,
          date: '9th',
          day: 'Sunday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"Mitch Lies"',
        },
        {
          id: 5,
          date: '14th',
          day: 'Friday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"Leanne McClellan Band"',
        },
        {
          id: 6,
          date: '15th',
          day: 'Saturday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"Ted Vaughn Blues Band"',
        },
        {
          id: 9,
          date: '28th',
          day: 'Friday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"DRTR Blues Band"',
        },
        {
          id: 10,
          date: '29th',
          day: 'Saturday',
          month: 'August',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie / Mike Renwick Duo"',
        },
      ],
      september: [
        {
          id: 2,
          date: '5th',
          day: 'Saturday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Ted Vaughn Blues Band"',
        },
        {
          id: 3,
          date: '11th',
          day: 'Friday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie Trio"',
        },
        {
          id: 4,
          date: '12th',
          day: 'Saturday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"The Dead Band"',
        },
        {
          id: 6,
          date: '19th',
          day: 'Saturday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Ted Vaughn Blues Band"',
        },
        {
          id: 7,
          date: '20th',
          day: 'Sunday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Mitch Lies"',
        },
        {
          id: 8,
          date: '26th',
          day: 'Saturday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Out of This World Band"',
        },
      ],
      october: [
        {
          id: 30,
          date: '30th',
          day: 'Friday',
          month: 'March',
          start: '2pm',
          end: '4pm',
          title: '"Rewind Band"',
        },
      ],
    },
  },
};

const eventReducer = (state = initState, action) => {
  // switch (action.type) {
  //   case 'CREATE_EVENT':
  //     console.log('created event', action.event);
  // }
  return state;
};

export default eventReducer;
