const initState = {
  // TODO: incorporate link to artist site if available
  events: {
    month: {
      september: [
        {
          id: 3,
          date: '11th',
          day: 'Friday',
          month: 'September',
          start: '6pm',
          end: '9pm',
          title: '"Orvil Ivie Trio"',
        },
        {
          id: 4,
          date: '12th',
          day: 'Saturday',
          month: 'September',
          start: '6pm',
          end: '9pm',
          title: '"The Dead Band"',
        },
        {
          id: 10,
          date: '13th',
          day: 'Sunday',
          month: 'September',
          start: '2pm',
          end: '5pm',
          title: '"Rewind Band"',
        },
        {
          id: 11,
          date: '18th',
          day: 'Friday',
          month: 'September',
          start: '6pm',
          end: '9pm',
          title: '"DRTR Blues"',
        },
        {
          id: 6,
          date: '19th',
          day: 'Saturday',
          month: 'September',
          start: '6pm',
          end: '9pm',
          title: '"Ted Vaughn Blues Band"',
        },
        {
          id: 7,
          date: '20th',
          day: 'Sunday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Mitch Lies"',
        },
        {
          id: 12,
          date: '25th',
          day: 'Friday',
          month: 'September',
          start: '6pm',
          end: '9pm',
          title: '"Rewind"',
        },
        {
          id: 8,
          date: '26th',
          day: 'Saturday',
          month: 'September',
          start: '6pm',
          end: '9pm',
          title: '"Out of This World Band"',
        },
        {
          id: 13,
          date: '27th',
          day: 'Sunday',
          month: 'September',
          start: '2pm',
          end: '4pm',
          title: '"Greg Ernst"',
        },
      ],
      october: [
        {
          id: 3,
          date: '4th',
          day: 'Sunday',
          month: 'October',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 1,
          date: '9th',
          day: 'Friday',
          month: 'October',
          start: '6pm',
          end: '9pm',
          title: '"DRTR Blues"',
        },
        {
          id: 2,
          date: '10th',
          day: 'Saturday',
          month: 'October',
          start: '6pm',
          end: '9pm',
          title: '"Rewind"',
        },
        {
          id: 4,
          date: '11th',
          day: 'Sunday',
          month: 'October',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 5,
          date: '18th',
          day: 'Sunday',
          month: 'October',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 6,
          date: '25th',
          day: 'Sunday',
          month: 'October',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 30,
          date: '30th',
          day: 'Friday',
          month: 'October',
          start: '6pm',
          end: '9pm',
          title: '"Rewind Band"',
        },
        {
          id: 31,
          date: '31st',
          day: 'Saturday',
          month: 'October',
          start: '6pm',
          end: '9pm',
          title: '"Orvil Ivie Trio"',
        },
      ],
      november: [
        {
          id: 1,
          date: '1st',
          day: 'Sunday',
          month: 'November',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 2,
          date: '8th',
          day: 'Sunday',
          month: 'November',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 3,
          date: '15th',
          day: 'Sunday',
          month: 'November',
          start: '1pm',
          end: '4pm',
          title: '"Rewind"',
        },
        {
          id: 4,
          date: '22nd',
          day: 'Sunday',
          month: 'November',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
        {
          id: 5,
          date: '29th',
          day: 'Sunday',
          month: 'November',
          start: '2pm',
          end: '4pm',
          title: '"Orvil Ivie"',
        },
      ],
    },
  },
};

const eventReducer = (state = initState, action) => {
  // switch (action.type) {
  //   case 'CREATE_EVENT':
  //     console.log('created event', action.event);
  // }
  return state;
};

export default eventReducer;
